version: '3.3'
services: 
  db: 
   build: server/
   image: kovalilya/test:db
   ports:
    - 4000:4000
  app:
   build: client/
   image: kovalilya/test:app
   ports:
    - 3000:3000
   depends_on:
    - db
